/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/aside/aside.vue')['default']
    Bar: typeof import('./src/components/echarts/barChart/Basic Bar.vue')['default']
    'Basic Bar': typeof import('./src/components/echarts/barChart/Basic Bar.vue')['default']
    'Basic Scatter Chart': typeof import('./src/components/echarts/ScatterChart/Basic Scatter Chart.vue')['default']
    Chart: typeof import('./src/components/echarts/lineChart/Smoothed Line Chart.vue')['default']
    Container: typeof import('./src/components/backup/container.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    Header: typeof import('./src/components/header/header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Smoothed Line Chart': typeof import('./src/components/echarts/lineChart/Smoothed Line Chart.vue')['default']
    Table: typeof import('./src/components/Elplus/Virtualized Table.vue')['default']
    'Virtualized Table': typeof import('./src/components/Elplus/Virtualized Table.vue')['default']
  }
}
